package com.saurabh.artifact.security

import cash.z.ecc.android.bip39.Mnemonics.MnemonicCode
import cash.z.ecc.android.bip39.Mnemonics.WordCount
import cash.z.ecc.android.bip39.toSeed

/**
 * Generates and validates BIP-39 mnemonic phrases for recovery.
 * Uses cryptographically secure random number generation (SecureRandom)
 * and the kotlin-bip39 library for standard compliance.
 */
object MnemonicGenerator {

    /**
     * Generates a new cryptographically secure 12-word mnemonic phrase.
     * Uses 128 bits of entropy generated by [java.security.SecureRandom].
     * 
     * @param wordCount The desired length of the mnemonic (default is 12 words).
     */
    fun generateMnemonic(wordCount: WordCount = WordCount.COUNT_12): List<String> {
        return MnemonicCode(wordCount).use { code ->
            code.toList()
        }
    }

    /**
     * Validates if a mnemonic phrase is a valid BIP-39 sequence with a correct checksum.
     */
    fun validateMnemonic(words: List<String>): Boolean {
        return try {
            val phrase = words.joinToString(" ")
            MnemonicCode(phrase).use { code ->
                code.validate()
                true
            }
        } catch (e: Exception) {
            false
        }
    }

    /**
     * Converts a mnemonic phrase to a deterministic seed for key derivation.
     * Follows BIP-39 standard: PBKDF2 with 2048 iterations and HMAC-SHA512.
     *
     * @param words The mnemonic phrase as a list of words.
     * @param passphrase Optional salt for the seed derivation.
     */
    fun toSeed(words: List<String>, passphrase: String = ""): ByteArray {
        val mnemonicChars = words.joinToString(" ").toCharArray()
        val passphraseChars = passphrase.toCharArray()
        
        return try {
            MnemonicCode(mnemonicChars).use { code ->
                code.toSeed(passphraseChars)
            }
        } finally {
            // Best effort to clear sensitive data from memory
            mnemonicChars.fill('\u0000')
            passphraseChars.fill('\u0000')
        }
    }
}
