package com.saurabh.artifact.model

import kotlinx.serialization.Serializable

/**
 * Describes the conversational energy and expression style of an artifact.
 * Distinct from emotions, which describe how the user feels.
 */
@Serializable
enum class ConversationStyle(
    val label: String,
    val description: String,
    val iconEmoji: String,
    val energyLevel: EnergyLevel
) {
    STORYTELLING(
        "Storytelling",
        "A narrative experience with a beginning, middle, and end.",
        "📖",
        EnergyLevel.MEDIUM
    ),
    REFLECTIVE(
        "Reflective",
        "Deep introspection and internal questioning.",
        "🤔",
        EnergyLevel.LOW
    ),
    RANT(
        "Rant",
        "Raw emotional venting and unfiltered expression.",
        "🔥",
        EnergyLevel.HIGH
    ),
    FUNNY(
        "Funny",
        "A humorous or lighthearted experience.",
        "😂",
        EnergyLevel.HIGH
    ),
    COMFORT(
        "Comfort",
        "Soft, vulnerable sharing meant to provide warmth.",
        "🫂",
        EnergyLevel.LOW
    ),
    CHAOTIC(
        "Chaotic",
        "High energy, rapid shifts, and raw emotional movement.",
        "🌀",
        EnergyLevel.HIGH
    ),
    ADVICE(
        "Advice",
        "Sharing lessons, perspective, or guidance.",
        "💡",
        EnergyLevel.MEDIUM
    ),
    LATE_NIGHT(
        "Late Night Thoughts",
        "Calm, quiet monologue, often recorded in solitude.",
        "🌙",
        EnergyLevel.LOW
    ),
    STREAM_OF_CONSCIOUSNESS(
        "Stream of Consciousness",
        "Raw, wandering thoughts without a fixed destination.",
        "🌊",
        EnergyLevel.MEDIUM
    )
}

/**
 * Energy levels help determine emotional pacing and listening modes.
 */
enum class EnergyLevel {
    LOW,    // Calm, quiet, bedtime-friendly
    MEDIUM, // Engaging, standard conversational pace
    HIGH    // Intense, loud, or rapid-fire
}

/**
 * Metadata specifically related to conversation styles for an Artifact.
 */
@Serializable
data class ArtifactConversationMetadata(
    var primaryStyle: ConversationStyle? = null,
    var secondaryStyles: List<ConversationStyle> = emptyList(),
    var aiSuggestions: List<StyleSuggestion> = emptyList(),
    var moderationState: StyleModerationState = StyleModerationState.SAFE,
    var isAIGenerated: Boolean = false
)

/**
 * A style suggestion generated by the AI analyzer.
 */
@Serializable
data class StyleSuggestion(
    var style: ConversationStyle,
    var confidence: Float,
    var reasoning: String? = null
)

/**
 * Moderation state for styles, specifically to handle volatile or sensitive combinations.
 */
enum class StyleModerationState {
    SAFE,
    SENSITIVE,      // Might need a trigger warning or soft distribution
    VOLATILE,       // High rant energy + sensitive topics
    RESTRICTED      // Violates safety guidelines
}

/**
 * Defines a listening mode preference for the user.
 */
@Serializable
data class ListeningMode(
    val id: String,
    val name: String,
    val allowedEnergyLevels: Set<EnergyLevel>,
    val preferredStyles: Set<ConversationStyle> = emptySet(),
    val excludedStyles: Set<ConversationStyle> = emptySet()
) {
    companion object {
        val BEDTIME = ListeningMode(
            id = "bedtime",
            name = "Bedtime Listening",
            allowedEnergyLevels = setOf(EnergyLevel.LOW),
            excludedStyles = setOf(ConversationStyle.RANT, ConversationStyle.CHAOTIC)
        )
        
        val FOCUS = ListeningMode(
            id = "focus",
            name = "Deep Focus",
            allowedEnergyLevels = setOf(EnergyLevel.LOW, EnergyLevel.MEDIUM),
            preferredStyles = setOf(ConversationStyle.REFLECTIVE, ConversationStyle.LATE_NIGHT)
        )
        
        val ENERGY_BOOST = ListeningMode(
            id = "energy_boost",
            name = "Energy Boost",
            allowedEnergyLevels = setOf(EnergyLevel.HIGH),
            preferredStyles = setOf(ConversationStyle.FUNNY, ConversationStyle.CHAOTIC, ConversationStyle.RANT)
        )
    }
}
