package com.saurabh.artifact.model

import kotlinx.serialization.Serializable

/**
 * Describes the conversational energy and expression style of an artifact.
 * Distinct from emotions, which describe how the user feels.
 */
    @Serializable
    enum class ConversationStyle(
        val label: String,
        val description: String,
        @Suppress("unused") val iconEmoji: String,
        @Suppress("unused") val energyLevel: EnergyLevel,
    ) {
        REFLECTIVE(
            "Reflective",
            "Deep introspection and internal questioning.",
            "🤔",
            EnergyLevel.LOW
        ),
        @Suppress("unused")
        RANT(
            "Rant",
            "Raw emotional venting and unfiltered expression.",
            "🔥",
            EnergyLevel.HIGH
        ),
        @Suppress("unused")
        FUNNY(
            "Funny",
            "A humorous or lighthearted experience.",
            "😂",
            EnergyLevel.HIGH
        ),
        @Suppress("unused")
        CHAOTIC(
            "Chaotic",
            "High energy, rapid shifts, and raw emotional movement.",
            "🌀",
            EnergyLevel.HIGH
        ),
        @Suppress("unused")
        LATE_NIGHT(
            "Late Night Thoughts",
            "Calm, quiet monologue, often recorded in solitude.",
            "🌙",
            EnergyLevel.LOW
        ),
    }

/**
 * Energy levels help determine emotional pacing and listening modes.
 */
enum class EnergyLevel {
    LOW,    // Calm, quiet, bedtime-friendly
    MEDIUM, // Engaging, standard conversational pace
    HIGH    // Intense, loud, or rapid-fire
}

/**
 * Metadata specifically related to conversation styles for an Artifact.
 */
@Serializable
data class ArtifactConversationMetadata(
    var primaryStyle: ConversationStyle? = null,
    var secondaryStyles: List<ConversationStyle> = emptyList(),
    var aiSuggestions: List<StyleSuggestion> = emptyList(),
    var moderationState: StyleModerationState = StyleModerationState.SAFE,
    var isAIGenerated: Boolean = false
)

/**
 * A style suggestion generated by the AI analyzer.
 */
@Serializable
data class StyleSuggestion(
    var style: ConversationStyle,
    var confidence: Float,
    var reasoning: String? = null
)

/**
 * Moderation state for styles, specifically to handle volatile or sensitive combinations.
 */
enum class StyleModerationState {
    SAFE,
}

