package com.saurabh.artifact.model

import kotlinx.serialization.Serializable

/**
 * Represents a specific topic tag that can be attached to an artifact.
 */
@Serializable
data class TopicTag(
    val id: String = "",
    val label: String,
    val categoryId: String? = null,
    val usageCount: Int = 0,
    val isSystemGenerated: Boolean = false,
    val moderationState: TopicModerationState = TopicModerationState.APPROVED,
    val createdAt: Long = System.currentTimeMillis()
)

/**
 * Broad categories for topics to help with organization and filtering.
 */
@Serializable
data class TopicCategory(
    val id: String = "",
    val name: String,
    val description: String,
    val iconEmoji: String = "✨",
    val colorHex: String = "#FFB300"
)

/**
 * A suggestion generated by the AI based on transcript analysis.
 */
@Serializable
data class TopicSuggestion(
    val topicId: String? = null, // Null if it's a new proposed label
    val label: String,
    val confidence: Float,
    val reason: String? = null, // e.g., "Matches keyword 'anxiety'"
    val source: SuggestionSource = SuggestionSource.AI_EMBEDDING
)

enum class SuggestionSource {
    AI_EMBEDDING,
    KEYWORD_MATCH,
    EMOTION_INFERENCE
}

/**
 * Moderation state for user-created topics.
 */
@Serializable
enum class TopicModerationState {
    APPROVED,
    REJECTED,
    FLAGGED_FOR_REVIEW
}
