package com.saurabh.artifact.model

import kotlinx.serialization.Serializable
import com.google.firebase.Timestamp

/**
 * Represents a specific topic tag that can be attached to an artifact.
 */
@Serializable
data class TopicTag(
    val id: String = "",
    val label: String,
    val categoryId: String? = null,
    val usageCount: Int = 0,
    val isSystemGenerated: Boolean = false,
    val moderationState: TopicModerationState = TopicModerationState.APPROVED,
    val createdAt: Long = System.currentTimeMillis()
)

/**
 * Broad categories for topics to help with organization and filtering.
 */
@Serializable
data class TopicCategory(
    val id: String = "",
    val name: String,
    val description: String,
    val iconEmoji: String = "✨",
    val colorHex: String = "#FFB300"
)

/**
 * Metadata specifically related to topics for an Artifact.
 */
@Serializable
data class TopicMetadata(
    val topicIds: List<String> = emptyList(),
    val primaryTopicId: String? = null,
    val aiConfidence: Map<String, Float> = emptyMap(),
    val isIdentitySafe: Boolean = true
)

/**
 * A suggestion generated by the AI based on transcript analysis.
 */
@Serializable
data class TopicSuggestion(
    val topicId: String? = null, // Null if it's a new proposed label
    val label: String,
    val confidence: Float,
    val reason: String? = null, // e.g., "Matches keyword 'anxiety'"
    val source: SuggestionSource = SuggestionSource.AI_EMBEDDING
)

enum class SuggestionSource {
    AI_EMBEDDING,
    KEYWORD_MATCH,
    EMOTION_INFERENCE,
    USER_HISTORY
}

/**
 * Defines relationships between topics for semantic search and discovery.
 */
@Serializable
data class TopicRelationship(
    val fromTopicId: String,
    val toTopicId: String,
    val relationshipType: RelationshipType,
    val strength: Float = 1.0f
)

enum class RelationshipType {
    PARENT_OF,
    RELATED_TO,
    SYNONYM_OF,
    OPPOSITE_OF
}

/**
 * Moderation state for user-created topics.
 */
@Serializable
enum class TopicModerationState {
    PENDING,
    APPROVED,
    REJECTED,
    FLAGGED_FOR_REVIEW
}

/**
 * Tracks a user's affinity towards specific topics based on their interactions.
 */
@Serializable
data class UserTopicAffinity(
    val userId: String,
    val topicId: String,
    val score: Float, // Higher score means higher affinity
    val lastInteractionAt: Long = System.currentTimeMillis()
)

/**
 * Contextual data used to generate recommendations.
 */
data class RecommendationContext(
    val currentTopicAffinities: List<UserTopicAffinity>,
    val activeEmotions: List<String>,
    val timeOfDay: String? = null,
    val exclusionList: List<String> = emptyList() // Artifact IDs already seen
)
